### PR TITLE
Milestone 6 Friendships V2

### PR DESCRIPTION
**Pull request by kubilaycaglayan**
### Dear TSE,

**All business requirements are applied.**

1. Two rows implied.
2. Like counts, comments counts are visible.
3. Tests added.

### With all our respects...

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Changes Require❌
# 🙋‍♂️Team!!!
#### You have done a good job so far team, here are a few changes we have to make to get this project approved. You are missing some tests, let us capture those👨‍💻.
- User model
* [x] Kindly test these all your instance methods in the User model ie ```send_invitation(receiver)```, ```destroy_pending_invitation(sender)``` etc..
- Post model
* [x] Kindly test this class methods in the Post model ie ```self.visible_posts(current_user)```.
- Friendship
* [x] Kindly test this class methods in the Post model ie ```self.you_sent_invitation?(id1, id2)```,```self.you_got_invitation?(id2, id1)``` etc...


## That is it kindly make these changes and submit the project for review👨‍⚖️.
#### Happy coding👨‍💻
Addo Forison

**Comment by kubilaycaglayan** [comment]
Hello Forison,
Thank you very much for your code review, I just got it.
We already have all the things you noted down.
I don't understand...
Is it possible you didn't switch to the current branch?
With all my respect...

**Comment by Forison** [comment]
> Hello Forison,
> Thank you very much for your code review, I just got it.
> We already have all the things you noted down.
> I don't understand...
> Is it possible you didn't switch to the current branch?
> With all my respect...

Hi, I will send you my views on slack right away...

**Comment by kubilaycaglayan** [comment]
> * The users should be able to confirm or reject a friend request from another user.
> 
> * I only see this `This User Sent An Invitation To You, Check Your Page!` but how do I confirm or reject??

sit1_LI

**Comment by kubilaycaglayan** [comment]
> * UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

sit2

**Comment by kubilaycaglayan** [comment]
> * [ ]  PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)).
> 
> * The timeline should show the postings of the current user and his friends.

Screenshot 2020-06-04 21 51 35

**Comment by Forison** [comment]
> > * The users should be able to confirm or reject a friend request from another user.
> > * I only see this `This User Sent An Invitation To You, Check Your Page!` but how do I confirm or reject??
> 
> sit1_LI

mypage
youInvitsent
branch


> > * [ ]   PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)).
> > * The timeline should show the postings of the current user and his friends.
> 
> Screenshot 2020-06-04 21 51 35
this is the branch name
branch

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap: Just one more thing to do
- [x] Write unit test for comments
#### You can go ahead and merge once you re done !!!

**Pull request merged**
