### PR TITLE
Milestone-1: Data Architecture

### PR DESCRIPTION
**Pull request by kubilaycaglayan**
Dear TSE,

1. We created our data plan on lucid diagrams. :heavy_check_mark: 
2. Saved the files in docs folder. :heavy_check_mark: 

With all our respects...

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @kubilaycaglayan and @mariosknl 
### You have done great so far :clap: However, you have a few changes to work on before your application can be approved.
- [ ] In the user records, add image column
### NOTE: You have done more than asked for in this milestone. It is always good to follow instructions
### Make the changes and submit for another code review. Good luck!
- Happy coding

By Raymond
slack @iamraymond

**Comment by rOluochKe** [comment]
> Hello @kubilaycaglayan and @mariosknl
> 
> ### You have done great so far  However, you have a few changes to work on before your application can be approved.
> * [ ]  In the user records, add image column
> 
> ### NOTE: You have done more than asked for in this milestone. It is always good to follow instructions
> ### Make the changes and submit for another code review. Good luck!
> * Happy coding
> 
> By Raymond
> slack @IAmRaymond

### Hey guys, I have just realized, I made a mistake. Sorry, the project is built on top of the existing one.  Change the image column in users record and submit for another review.

**Comment by uryelah** [comment]
Hello guys, I'm Sarah, your reviewer for this PR 👩‍🚀  

---------    
    
Good job!

---------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by uryelah** [comment]
Hey guys, the file you need to change is actually he ERD diagram saved at docs/KubilayMarios.pdf

## Changes Required 🏗️ 🐛 💡

- [ ] Please add the user_image property to the diagram, not just the txt file.


-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work implementing the suggested changes :clap: :clap: However, I have noted some issues with your ERD diagram that you need to address in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** Friends table is supposed to act as a **join table** that connects users with their friends. Doing one relationship between the two tables like you did won't allow you to add two foreign keys. Each association signifies a single relationship (either a sender or a receiver). You need two relationships, one for the sender of the friend request and the other for the receiver.
- **[SUGGESTION]** Also it's an ERD design convention to name join tables after their relationships, for this case it's better to name it "Friendship".

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Review by mosaaleb — APPROVED** [review]
#### Well done @kubilaycaglayan @mariosknl :clap:

You can merge :+1: 

##### Muhammad Ebeid

**Pull request merged**
